### ISSUE TITLE
Uncaught TypeError: Cannot read property 'printWidth' of undefined

### ISSUE THREAD

**Issue by ronnyvv** [cmstead/js-refactor-atom#3]
[Enter steps to reproduce:]

1. Selected some code inside a named function
2. Selected "Wrap Selection in function"

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: [js-refactor-atom](https://github.com/cmstead/js-refactor-atom) package 0.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'printWidth' of undefined

```
At /home/rvindenes/.atom/packages/js-refactor-atom/lib/modules/commands/reformatFactory.js:13

TypeError: Cannot read property 'printWidth' of undefined
    at buildOptions (/packages/js-refactor-atom/lib/modules/commands/reformatFactory.js:13:72)
    at /packages/js-refactor-atom/lib/modules/commands/reformatFactory.js:22:28
    at /packages/js-refactor-atom/lib/js-refactor-atom.js:92:17
    at Object.applySetEdit (/packages/js-refactor-atom/lib/modules/shared/editActionsFactory.js:15:30)
    at applyToDocument (/packages/js-refactor-atom/lib/modules/commands/generic/wrapInTemplateFactory.js:26:53)
    at /packages/js-refactor-atom/lib/modules/shared/dialogFactory.js:12:7
    at /packages/js-refactor-atom/lib/modules/shared/dialog.js:138:9
    at Array.map (native)
    at Dialog.onConfirm (/packages/js-refactor-atom/lib/modules/shared/dialog.js:137:32)
    at /packages/js-refactor-atom/lib/modules/shared/dialog.js:76:24)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:33.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:42.3.0 core:close (div.package-detail.panels-item)
     -0:34.7.0 js-refactor-atom:wrapInFunction (span.syntax--string.syntax--regexp.syntax--js)
     -0:26.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
atom-beautify 0.30.6 
atom-ide-ui 0.6.0 
autocomplete-modules 1.8.0 
editorconfig 2.2.2 
file-icons 2.1.14 
fonts 3.0.3 
git-blame 1.3.1 
git-time-machine 1.5.9 
gl-light-syntax 3.0.0 
ide-css 0.2.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-typescript 0.7.0 
ide-yaml 0.4.1 
js-refactor-atom 0.10.1 
language-babel 2.79.0 
language-ejs 0.4.0 
linter-eslint 8.4.0 
pigments 0.40.2 
project-manager 3.3.5 
project-sidebar 1.3.0 
sync-settings 0.8.3 
teletype 0.1.4 
wordcount 2.10.4 
```

**Comment by cmstead** [comment]
Hi Ronny, thanks for sending me this issue. I'm in the middle of reworking the innards of the refactoring tool, so it may take me a little while to fully resolve this.  In the meanwhile would it be possible to have a sample of the code that this failure occurred within? In the past there have been some issues around transpile-to-JS languages like JSX, so example code will help me pin down the cause.

Side note, the formatting is done with Prettier, so I will explore everything which might introduce an issue within my code, however if there is a deeper issue I might have to work with you to explore this with the Prettier folks, but we'll have to see where the exploration goes.

**Comment by ronnyvv** [comment]
While trying to find a minimal example that would trigger the error I discovered that going into Settings for the plugin and simply clicking in the Print Width input field (without entering any value) and Tab Width, the problem disappeared. It looks like installing the plugin didn't create `  "js-refactor-atom": {}` in my config and so https://github.com/cmstead/js-refactor-atom/blob/master/lib/modules/commands/reformatFactory.js#L11 was called with `config === undefined`

**Comment by cmstead** [comment]
Oh! That's super helpful. I think I can fix that pretty easily. Thanks for the updated info!
